### ISSUE TITLE
svg navigation map

### ISSUE THREAD

**Issue by lee2512** [LukeOwncloud/SvgNaviMap#9]
hie. i am trying to develop an indoor svg navigation map for a building to that it can be viewed on an android phone. according to your document, it states that if i use this application you have provided i have the ability to use any position provider. in my case i want to use LEDs, a technology called Visible Light Technology. i am having a problem trying to understand how you use the code you provided. i am new to the whole programming thing. from the files you have provided, i only know that the android file is meant to be put in my android development area and in this case i am using android studio.as for all the other files and folders, i have no idea where i have to put them.if you could provide me with a step by step way i can implement this it will be very usefull. i have already created my svg map using adobe illustrator.

**Comment by LukeOwncloud** [comment]
Please refer to https://github.com/LukeOwncloud/SvgNaviMap#usage
If anything is left unclear please ask **specific** questions. Choose a meaningful title.
